+CSCI_GrpDesktop = True
universe = vanilla
executable   = /bin/bash
arguments = timm_model.sh
getenv = True
Requirements = (Machine == "kb307-07@cs.wwu.edu")

# arguments    =

# Where Condor writes stdout/stderr/log
output       = /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/outputs/timm_model/timm_model_hard.out
log          = /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/outputs/timm_model/timm_model_hard.log
error          = /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/outputs/timm_model/timm_model_hard.err

# resource requests

request_GPUs       = 1
gpus_minimum_memory = 8GB
request_cpus    = 8
request_memory  = 32GB
request_disk    = 32GB
# file transfer

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
# /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main 
transfer_input_files = \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/src/timm_model.py, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/src/helper_loads, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/main.py, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/jobs/timm_model/timm_model.sh, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/venv_package/torch_venv2.tar.gz, \

# queue 
queue 1
