+CSCI_GrpDesktop = True
universe = vanilla
executable = /bin/bash
arguments = rs_xception_h.sh 
getenv = True
Requirements = HasLocal581 == True

# Where Condokr writes stdout/stderr/log
output       = /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/outputs/rs_xception/rs_xception.out
log          = /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/outputs/rs_xception/rs_xception.log
error          = /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/outputs/rs_xception/rs_xception.err

# resource requests

request_GPUs       = 1
gpus_minimum_memory = 8GB
request_cpus    = cpus 
request_memory  = 16GB 
request_disk    = 16GB

# file transfer

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
# transfer_output_files = xception_1.txt,xception_2.txt,xception_3.txt,xception_4.txt,xception_5.txt,xception_6.txt,xception_7.txt,xception_8.txt,xception_9.txt,xception_10.txt

transfer_input_files = \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/src/xception.py, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/experiments, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/src/helper_loads, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/main.py, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/jobs/rs_xception/rs_xception_h.sh, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/caller_bash_scripts/rs_xception.sh, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/venv_package/torch_venv2.tar.gz, 


# queue 
queue 1
