+CSCI_GrpDesktop = True
universe = vanilla
executable = /bin/bash
arguments = rs_vision_trans_h.sh 
getenv = True
Requirements = HasLocal581 == True

# Where Condokr writes stdout/stderr/log
output       = /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/outputs/rs_vision_trans/rs_vision_trans.out
log          = /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/outputs/rs_vision_trans/rs_vision_trans.log
error          = /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/outputs/rs_vision_trans/rs_vision_trans.err

# resource requests

request_GPUs       = 1
gpus_minimum_memory = 8GB
request_cpus    = cpus 
request_memory  = 16GB 
request_disk    = 16GB

# file transfer

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
# transfer_output_files = vision_trans_1.txt,vision_trans_2.txt,vision_trans_3.txt,vision_trans_4.txt,vision_trans_5.txt,vision_trans_6.txt,vision_trans_7.txt,vision_trans_8.txt,vision_trans_9.txt,vision_trans_10.txt

transfer_input_files = \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/src/vision_trans.py, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/experiments, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/src/helper_loads, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/main.py, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/jobs/rs_vision_trans/rs_vision_trans_h.sh, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/main/caller_bash_scripts/rs_vision_trans.sh, \
  /home/username/MAIN/dev/CS481/final_project/202610_csci581_project_gel_han_tri/code/task4/condor/venv_package/torch_venv2.tar.gz, 


# queue 
queue 1
